### ISSUE TITLE
mysql

### ISSUE THREAD

**Issue by Pastew** [alinturbut/olxCrawl#1]
Hi,

this app requires runnin mySQL server?

I am asking because I found this in application.properties file:
spring.datasource.url=jdbc:mysql://localhost:3306/olxcrawl

**Comment by alinturbut** [comment]
Hello, 

Yes mysql/mariadb server running locally at 3306 is required.

**Comment by Pastew** [comment]
Thanks for response. You may consider adding information about this to readme to save others time, like me. For example I originally thought that this app will run as standalone (using SQLite for example).
#2
